<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="MessagingService.Client" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.Abstractions" />
    <PackageReference Include="OpenIddict.Server" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="Shared.Logger" />
    <PackageReference Include="Shared.Results" />
    <PackageReference Include="SimpleResults" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SecurityService.Database\SecurityService.Database.csproj" />
    <ProjectReference Include="..\SecurityService.DataTransferObjects\SecurityService.DataTransferObjects.csproj" />
    <ProjectReference Include="..\SecurityService.Models\SecurityService.Models.csproj" />
  </ItemGroup>
</Project>
