// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SecurityService.IntegrationTests.ApiResource
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ApiResource")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [NUnit.Framework.CategoryAttribute("base")]
    [NUnit.Framework.CategoryAttribute("apiresources")]
    public partial class ApiResourceFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "apiresources"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ApiResource", "ApiResource", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "ApiResource.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get Api Resources")]
        [NUnit.Framework.CategoryAttribute("PRTest")]
        public async System.Threading.Tasks.Task GetApiResources()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get Api Resources", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Description",
                            "Secret",
                            "Scopes",
                            "UserClaims"});
                table1.AddRow(new string[] {
                            "testresource1",
                            "Test Resource1",
                            "A resource for testing 1",
                            "secret1",
                            "Scope1,Scope2",
                            "Claim1,Claim2"});
                table1.AddRow(new string[] {
                            "testresource2",
                            "Test Resource2",
                            "A resource for testing 2",
                            "secret2",
                            "Scope1,Scope2",
                            "Claim1,Claim2"});
#line 6
await testRunner.GivenAsync("I create the following api resources", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Description",
                            "Scopes",
                            "UserClaims"});
                table2.AddRow(new string[] {
                            "testresource1",
                            "Test Resource1",
                            "A resource for testing 1",
                            "Scope1,Scope2",
                            "Claim1,Claim2"});
#line 10
await testRunner.WhenAsync("I get the api resource with name \'testresource1\' the api resource details are ret" +
                        "urned as follows", ((string)(null)), table2, "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Description",
                            "Scopes",
                            "UserClaims"});
                table3.AddRow(new string[] {
                            "testresource2",
                            "Test Resource2",
                            "A resource for testing 2",
                            "Scope1,Scope2",
                            "Claim1,Claim2"});
#line 13
await testRunner.WhenAsync("I get the api resource with name \'testresource2\' the api resource details are ret" +
                        "urned as follows", ((string)(null)), table3, "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Description",
                            "Scopes",
                            "UserClaims"});
                table4.AddRow(new string[] {
                            "testresource1",
                            "Test Resource1",
                            "A resource for testing 1",
                            "Scope1,Scope2",
                            "Claim1,Claim2"});
                table4.AddRow(new string[] {
                            "testresource2",
                            "Test Resource2",
                            "A resource for testing 2",
                            "Scope1,Scope2",
                            "Claim1,Claim2"});
#line 16
await testRunner.WhenAsync("I get the api resources 2 api resource details are returned as follows", ((string)(null)), table4, "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
