// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SecurityService.IntegrationTests.Clients
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "base")]
    [Xunit.TraitAttribute("Category", "clients")]
    public partial class ClientsFeature : object, Xunit.IClassFixture<ClientsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "base",
                "clients"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Clients.feature"
#line hidden
        
        public ClientsFeature(ClientsFeature.FixtureData fixtureData, SecurityService_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Clients", "Clients", null, ProgrammingLanguage.CSharp, new string[] {
                        "base",
                        "clients"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create Client")]
        [Xunit.TraitAttribute("FeatureTitle", "Clients")]
        [Xunit.TraitAttribute("Description", "Create Client")]
        public virtual void CreateClient()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create Client", null, tagsOfScenario, argumentsOfScenario);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClientId",
                            "Name",
                            "Description",
                            "Secret",
                            "Scopes",
                            "GrantTypes",
                            "RedirectUris",
                            "PostLogoutRedirectUris",
                            "RequireConsent"});
                table11.AddRow(new string[] {
                            "testclient1",
                            "Test Client",
                            "A test client",
                            "secret1",
                            "Scope1, Scope2",
                            "client_credentials",
                            "",
                            "",
                            ""});
                table11.AddRow(new string[] {
                            "testclient2",
                            "Test Client 2",
                            "A second test client",
                            "Secret2",
                            "Scope1, Scope2",
                            "authorization_code",
                            "http://localhost/signin-oidc",
                            "http://localhost/signout-oidc",
                            "true"});
#line 5
 testRunner.Given("I create the following clients", ((string)(null)), table11, "Given ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get Client")]
        [Xunit.TraitAttribute("FeatureTitle", "Clients")]
        [Xunit.TraitAttribute("Description", "Get Client")]
        public virtual void GetClient()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Client", null, tagsOfScenario, argumentsOfScenario);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClientId",
                            "Name",
                            "Description",
                            "Secret",
                            "Scopes",
                            "GrantTypes",
                            "RedirectUris",
                            "PostLogoutRedirectUris",
                            "RequireConsent"});
                table12.AddRow(new string[] {
                            "testclient1",
                            "Test Client 1",
                            "A test client 1",
                            "secret1",
                            "Scope1, Scope2",
                            "client_credentials",
                            "",
                            "",
                            ""});
                table12.AddRow(new string[] {
                            "testclient2",
                            "Test Client 2",
                            "A second test client",
                            "Secret2",
                            "Scope1, Scope2",
                            "authorization_code",
                            "http://localhost/signin-oidc",
                            "http://localhost/signout-oidc",
                            "true"});
#line 11
 testRunner.Given("I create the following clients", ((string)(null)), table12, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClientId",
                            "Name",
                            "Description",
                            "Scopes",
                            "GrantTypes",
                            "RedirectUris",
                            "PostLogoutRedirectUris",
                            "RequireConsent"});
                table13.AddRow(new string[] {
                            "testclient1",
                            "Test Client 1",
                            "A test client 1",
                            "Scope1, Scope2",
                            "client_credentials",
                            "",
                            "",
                            ""});
#line 16
 testRunner.When("I get the client with client id \'testclient1\' the client details are returned as " +
                        "follows", ((string)(null)), table13, "When ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClientId",
                            "Name",
                            "Description",
                            "Scopes",
                            "GrantTypes",
                            "RedirectUris",
                            "PostLogoutRedirectUris",
                            "RequireConsent"});
                table14.AddRow(new string[] {
                            "testclient2",
                            "Test Client 2",
                            "A second test client",
                            "Scope1, Scope2",
                            "authorization_code",
                            "http://localhost/signin-oidc",
                            "http://localhost/signout-oidc",
                            "true"});
#line 20
 testRunner.When("I get the client with client id \'testclient2\' the client details are returned as " +
                        "follows", ((string)(null)), table14, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get Clients")]
        [Xunit.TraitAttribute("FeatureTitle", "Clients")]
        [Xunit.TraitAttribute("Description", "Get Clients")]
        [Xunit.TraitAttribute("Category", "PRTest")]
        public virtual void GetClients()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Clients", null, tagsOfScenario, argumentsOfScenario);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClientId",
                            "Name",
                            "Description",
                            "Secret",
                            "Scopes",
                            "GrantTypes",
                            "RedirectUris",
                            "PostLogoutRedirectUris",
                            "RequireConsent"});
                table15.AddRow(new string[] {
                            "testclient1",
                            "Test Client 1",
                            "A test client 1",
                            "secret1",
                            "Scope1, Scope2",
                            "client_credentials",
                            "",
                            "",
                            ""});
                table15.AddRow(new string[] {
                            "testclient2",
                            "Test Client 2",
                            "A second test client",
                            "Secret2",
                            "Scope1, Scope2",
                            "authorization_code",
                            "http://localhost/signin-oidc",
                            "http://localhost/signout-oidc",
                            "true"});
#line 26
 testRunner.Given("I create the following clients", ((string)(null)), table15, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "ClientId",
                            "Name",
                            "Description",
                            "Scopes",
                            "GrantTypes",
                            "RedirectUris",
                            "PostLogoutRedirectUris",
                            "RequireConsent"});
                table16.AddRow(new string[] {
                            "testclient1",
                            "Test Client 1",
                            "A test client 1",
                            "Scope1, Scope2",
                            "client_credentials",
                            "",
                            "",
                            ""});
                table16.AddRow(new string[] {
                            "testclient2",
                            "Test Client 2",
                            "A second test client",
                            "Scope1, Scope2",
                            "authorization_code",
                            "http://localhost/signin-oidc",
                            "http://localhost/signout-oidc",
                            "true"});
#line 31
 testRunner.When("I get the clients 2 clients details are returned as follows", ((string)(null)), table16, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ClientsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ClientsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
