// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SecurityService.IntegrationTests.IdentityResource
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "base")]
    [Xunit.TraitAttribute("Category", "identityresources")]
    public partial class IdentityResourceFeature : object, Xunit.IClassFixture<IdentityResourceFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "identityresources"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "IdentityResource.feature"
#line hidden
        
        public IdentityResourceFeature(IdentityResourceFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "IdentityResource", "IdentityResource", null, ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get Identity Resources")]
        [Xunit.TraitAttribute("FeatureTitle", "IdentityResource")]
        [Xunit.TraitAttribute("Description", "Get Identity Resources")]
        [Xunit.TraitAttribute("Category", "PRTest")]
        public async System.Threading.Tasks.Task GetIdentityResources()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("Get Identity Resources", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                Reqnroll.Table table13 = new Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Description",
                            "UserClaims"});
                table13.AddRow(new string[] {
                            "testresource1",
                            "Test Resource1",
                            "A resource for testing 1",
                            "Claim1,Claim2"});
                table13.AddRow(new string[] {
                            "testresource2",
                            "Test Resource2",
                            "A resource for testing 2",
                            "Claim1,Claim2"});
#line 6
 await testRunner.GivenAsync("I create the following identity resources", ((string)(null)), table13, "Given ");
#line hidden
                Reqnroll.Table table14 = new Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Description",
                            "UserClaims"});
                table14.AddRow(new string[] {
                            "testresource1",
                            "Test Resource1",
                            "A resource for testing 1",
                            "Claim1,Claim2"});
#line 10
 await testRunner.WhenAsync("I get the identity resource with name \'testresource1\' the identity resource detai" +
                        "ls are returned as follows", ((string)(null)), table14, "When ");
#line hidden
                Reqnroll.Table table15 = new Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Description",
                            "UserClaims"});
                table15.AddRow(new string[] {
                            "testresource2",
                            "Test Resource2",
                            "A resource for testing 2",
                            "Claim1,Claim2"});
#line 13
 await testRunner.WhenAsync("I get the identity resource with name \'testresource2\' the identity resource detai" +
                        "ls are returned as follows", ((string)(null)), table15, "When ");
#line hidden
                Reqnroll.Table table16 = new Reqnroll.Table(new string[] {
                            "Name",
                            "DisplayName",
                            "Description",
                            "UserClaims"});
                table16.AddRow(new string[] {
                            "testresource1",
                            "Test Resource1",
                            "A resource for testing 1",
                            "Claim1,Claim2"});
                table16.AddRow(new string[] {
                            "testresource2",
                            "Test Resource2",
                            "A resource for testing 2",
                            "Claim1,Claim2"});
#line 16
 await testRunner.WhenAsync("I get the identity resources 2 identity resource details are returned as follows", ((string)(null)), table16, "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await IdentityResourceFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await IdentityResourceFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
