<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="HtmlAgilityPack" />

    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />

    <PackageReference Include="Microsoft.NET.Test.Sdk" />

    <PackageReference Include="Reqnroll" />

    <PackageReference Include="Reqnroll.Tools.MsBuild.Generation" />

    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Reqnroll.NUnit" />

    <PackageReference Include="Selenium.Support" />
    <PackageReference Include="Selenium.WebDriver" />
    <PackageReference Include="Shared.IntegrationTesting" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Ductus.FluentDocker" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecurityService.Client\SecurityService.Client.csproj" />
    <ProjectReference Include="..\SecurityService.DataTransferObjects\SecurityService.DataTransferObjects.csproj" />
    <ProjectReference Include="..\SecurityService.IntegrationTesting.Helpers\SecurityService.IntegrationTesting.Helpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="UserLogin\UserLogin.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </None>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
