<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <UserSecretsId>66711dd1-58c4-40cb-9a4c-2119de1f1d56</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Pages\Account\ExternalLogin\Index.cshtml.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Pages\Account\ExternalLogin\Index.cshtml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="Shared" />
    <PackageReference Include="Shared.Results.Web" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Sentry.AspNetCore" />
    <PackageReference Include="NLog.Web.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SecurityService.BusinessLogic\SecurityService.BusinessLogic.csproj" />
    <ProjectReference Include="..\SecurityService.Database\SecurityService.Database.csproj" />
    <ProjectReference Include="..\SecurityService.DataTransferObjects\SecurityService.DataTransferObjects.csproj" />
    <ProjectReference Include="..\SecurityService.Models\SecurityService.Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.staging.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="hosting.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="aspnetapp-root-cert.cer">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="aspnetapp-web-api.pfx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Pages\Account\ExternalLogin\" />
  </ItemGroup>
</Project>
