name: Code Coverage

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  workflow_dispatch:

jobs:  
  build:
    name: "Code Coverage"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4    

    - name: Restore Nuget Packages
      run: dotnet restore SecurityService.slnx --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}
        
    - name: Build Code
      run: dotnet build SecurityService.slnx --configuration Release

    - name: Run Unit Tests
      working-directory: SecurityService.UnitTests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "SecurityService.UnitTests.csproj" --configuration Release --verbosity normal --coverage --coverage-output-format cobertura --results-directory TestResults

    - name: Upload coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./SecurityService.UnitTests/TestResults/*.cobertura.xml
